name: Deploy static resume to Azure Web App - cloudresumex-bhanuvardhan

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Required for OIDC login
      contents: read # Required for checkout

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Login to Azure using OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5E8CA1EE57EA458990C2DD024F58FA34 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4198A12AF8D645AFB53D9BAF87F7D3A4 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2A18F1F1468C40A583F5E312A5EE9FBC }}

      - name: Deploy static content to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "cloudresumex-bhanuvardhan"
          slot-name: "Production"
          package: .
